version: "3.8"

services:
  mistral_backdoor:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mistral_backdoor
    volumes:
      - ./mistral_models:/app/mistral_models  # Monte le dossier des modèles locaux
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]  # Active le GPU si disponible
    tty: true  # Permet d'interagir avec le container
    stdin_open: true  # Garde le container ouvert pour l'interaction
    environment:
      - PYTHONUNBUFFERED=1  # Désactive le buffer pour les logs Python
