services:
  mistral_backdoor:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mistral_backdoor
    # Augmente la mémoire partagée pour éviter les erreurs de DataLoader (ex: PyTorch)
    shm_size: '2gb' 
    volumes:
      - ./mistral_models:/app/mistral_models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    tty: true
    stdin_open: true
    environment:
      - PYTHONUNBUFFERED=1
      # Optionnel : Force l'utilisation du GPU 0 si vous en avez plusieurs
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility